import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { getSession } from "@/lib/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Notes App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-gray-50 text-gray-900">
        <header className="bg-white border-b border-gray-200">
          <div className="max-w-5xl mx-auto px-4 sm:px-6 py-4 flex justify-between items-center">
            <Link href="/" className="text-xl font-bold text-blue-600 hover:text-blue-700">
              NotesApp
            </Link>
            <nav className="flex items-center space-x-6">
              {session ? (
                <>
                  <Link href="/" className="text-gray-600 hover:text-gray-900 font-medium">
                    All Notes
                  </Link>
                  <Link href="/notes/new" className="text-gray-600 hover:text-gray-900 font-medium">
                    New Note
                  </Link>
                  <div className="w-px h-6 bg-gray-300 mx-2"></div>
                  <span className="text-sm text-gray-500">{session.email}</span>
                  <Link href="/logout" className="text-sm text-red-600 hover:text-red-800 font-medium">
                    Log out
                  </Link>
                </>
              ) : (
                <>
                  <Link href="/login" className="text-gray-600 hover:text-gray-900 font-medium">
                    Log in
                  </Link>
                  <Link href="/register" className="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 font-medium text-sm transition">
                    Register
                  </Link>
                </>
              )}
            </nav>
          </div>
        </header>

        <main className="flex-1 w-full max-w-5xl mx-auto px-4 sm:px-6 py-8">
          {children}
        </main>

        <footer className="bg-white border-t border-gray-200 py-6 text-center text-sm text-gray-500">
          <p>© {new Date().getFullYear()} Notes App.</p>
        </footer>
      </body>
    </html>
  );
}
